### ISSUE TITLE
Start to create issues

### ISSUE THREAD

**Issue by pransteter** [reginaldojunior/wisdom-of-the-elephant#1]
Just do it for ourselves.
Sure?!

And other thing, please change your picture, put on a picture more nice, more cool, like pictures that you are with glasses, etc... etc...  
This avatar picture is a poor trash.

Late, delete this issue. For you, for me, for us.

bye bye. motherfucker.

**Comment by reginaldojunior** [comment]
Ok Bitch! Let's go code and translate.  :smile:

**Comment by reginaldojunior** [comment]
I don't know delete issues, and now?
